// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tfs.Api.Infrastructure.DbContexts;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(TfsApiDbContext))]
    [Migration("20240213190118_AudithRequestTraceMigration")]
    partial class AudithRequestTraceMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.AggregateModels.Projects.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DurationInMonths")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDateAndTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_Projects");

                    b.HasIndex("ClientId");

                    b.HasIndex("SectorId");

                    b.HasIndex(new[] { "Name" }, "UK_Projects_Name")
                        .IsUnique();

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Domain.AggregateModels.Projects.ProjectTechnology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("TechnologyId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_ProjectsTechnologies");

                    b.HasIndex("TechnologyId");

                    b.HasIndex(new[] { "ProjectId", "TechnologyId" }, "UK_ProjectsTechnologies_ProjectId_TechnologyId")
                        .IsUnique();

                    b.ToTable("ProjectsTechnologies", (string)null);
                });

            modelBuilder.Entity("Domain.AggregateModels.Technology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id")
                        .HasName("PK_Technologies");

                    b.HasIndex(new[] { "Name" }, "UK_Technologies_Name")
                        .IsUnique();

                    b.ToTable("Technologies", (string)null);
                });

            modelBuilder.Entity("Tfs.Api.Domain.AggretateModels.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id")
                        .HasName("PK_Clients");

                    b.HasIndex(new[] { "Name" }, "UK_Clients_Name")
                        .IsUnique();

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("Tfs.Api.Domain.AggretateModels.RequestTrace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAndTimeOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateAndTimeOfLastModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("NumberOfRequests")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_RequestTrace");

                    b.HasIndex(new[] { "IPAddress" }, "UK_RequestTrace_IPAddress")
                        .IsUnique();

                    b.ToTable("RequestTrace", (string)null);
                });

            modelBuilder.Entity("Tfs.Api.Domain.AggretateModels.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id")
                        .HasName("PK_Sectors");

                    b.HasIndex(new[] { "Name" }, "UK_Sectors_Name")
                        .IsUnique();

                    b.ToTable("Sectors", (string)null);
                });

            modelBuilder.Entity("Domain.AggregateModels.Projects.Project", b =>
                {
                    b.HasOne("Tfs.Api.Domain.AggretateModels.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Projects_Clients_ClientId");

                    b.HasOne("Tfs.Api.Domain.AggretateModels.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Projects_Sectors_SectorId");

                    b.Navigation("Client");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Domain.AggregateModels.Projects.ProjectTechnology", b =>
                {
                    b.HasOne("Domain.AggregateModels.Projects.Project", "Project")
                        .WithMany("ProjectTechnologies")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ProjectsTechnologies_Projects_ProjectId");

                    b.HasOne("Domain.AggregateModels.Technology", "Technology")
                        .WithMany()
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ProjectsTechnologies_Technology_TechnologyId");

                    b.Navigation("Project");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("Domain.AggregateModels.Projects.Project", b =>
                {
                    b.Navigation("ProjectTechnologies");
                });
#pragma warning restore 612, 618
        }
    }
}
